--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Aryanxxpro/BowParticle
build-by-default: true
branches:
- main
projects:
  BowParticle:
    libs:
      - src: jojoe77777/FormAPI/libFormAPI
        version: ^2.1.1
    path: ""
    icon: icon.png
...
